# ============================================
# DigitalOcean App Platform Configuration
# ============================================
# This file defines your app's infrastructure and deployment settings
# Documentation: https://docs.digitalocean.com/products/app-platform/

name: quoteshub
region: nyc

# ============================================
# DATABASE CONFIGURATION
# ============================================
databases:
  - name: db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: quoteshub-db

# ============================================
# WEB SERVICE CONFIGURATION
# ============================================
services:
  - name: web
    # GitHub Integration
    github:
      repo: https://github.com/ananikets18/thequoteshub  # Update this!
      branch: main
      deploy_on_push: true
    
    # Source Configuration
    source_dir: /
    
    # PHP Runtime
    environment_slug: php
    
    # Build Settings
    build_command: composer install --no-dev --optimize-autoloader
    
    # Run Command (Apache with mod_php)
    run_command: |
      sed -i 's/DocumentRoot \/app/DocumentRoot \/workspace/' /etc/apache2/sites-available/000-default.conf && \
      sed -i 's/\/app/\/workspace/' /etc/apache2/apache2.conf && \
      echo "DirectoryIndex index.php index.html" >> /etc/apache2/apache2.conf && \
      a2enmod rewrite && \
      apache2-foreground
    
    # HTTP Port
    http_port: 8080
    
    # Health Check
    health_check:
      http_path: /
    
    # Resource Configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # Start small, scale up if needed
    
    # Routes
    routes:
      - path: /
    
    # ============================================
    # ENVIRONMENT VARIABLES
    # ============================================
    envs:
      # Application Settings
      - key: APP_ENV
        scope: RUN_TIME
        value: "production"
      
      - key: APP_DEBUG
        scope: RUN_TIME
        value: "false"
      
      - key: APP_NAME
        scope: RUN_TIME
        value: "The Quotes Hub"
      
      - key: APP_URL
        scope: RUN_TIME
        value: "https://www.thequoteshub.info"
      
      # Database Configuration (Auto-injected from database component)
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db.PORT}
      
      - key: DB_USER
        scope: RUN_TIME
        value: ${db.USERNAME}
      
      - key: DB_PASS
        scope: RUN_TIME
        value: ${db.PASSWORD}
        type: SECRET
      
      - key: DB_NAME
        scope: RUN_TIME
        value: ${db.DATABASE}
      
      # Session Settings
      - key: SESSION_LIFETIME
        scope: RUN_TIME
        value: "7200"
      
      # Upload Settings
      - key: UPLOAD_MAX_SIZE
        scope: RUN_TIME
        value: "5242880"
      
      - key: ALLOWED_IMAGE_TYPES
        scope: RUN_TIME
        value: "jpg,jpeg,png,gif,webp"
      
      # PHP Settings
      - key: PHP_MEMORY_LIMIT
        scope: RUN_TIME
        value: "256M"
      
      - key: PHP_UPLOAD_MAX_FILESIZE
        scope: RUN_TIME
        value: "5M"
      
      - key: PHP_POST_MAX_SIZE
        scope: RUN_TIME
        value: "8M"

# ============================================
# STATIC SITE (Optional - for CDN)
# ============================================
static_sites:
  - name: assets
    github:
      repo: https://github.com/ananikets18/thequoteshub  # Update this!
      branch: main
      deploy_on_push: true
    source_dir: /public
    output_dir: /
    routes:
      - path: /public

# ============================================
# DOMAIN CONFIGURATION
# ============================================
domains:
  - domain: www.thequoteshub.info
    type: PRIMARY
  - domain: thequoteshub.info
    type: ALIAS

# ============================================
# FEATURES
# ============================================
features:
  - buildpack-stack=ubuntu-22
